### ISSUE TITLE
Create a secret with your own personal access token in AWS, link it to bucephalus.

### ISSUE THREAD

**Issue by GolanTrev** [Watts-Lab/daphme#7]
Try to make it private (so that I can't see your credentials), and let me know how that process works.

**Comment by GolanTrev** [comment]
Did you end up doing this? Can I close this?

**Comment by thom-li** [comment]
I gave this a shot, but I get the error

Failed to create secret.
User: arn:aws:iam::707813031043:user/thomas-li is not authorized to perform: secretsmanager:CreateSecret on resource: github-thomli because no identity-based policy allows the secretsmanager:CreateSecret action

Let me know if you're able to change authorizations and I can try again
